### ISSUE TITLE
Power saving features 

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-linux#38]
As listed in https://www.ti.com/lit/an/sprac74a/sprac74a.pdf:

- See Table 7 on page 26 - which peripherals can we kill?
- Disable USB1 (the peripheral and the PHY - seee page 34-36 DTS example)
- Disable Ethernet if not already (section 4.2.2)
- Graphics (SGX) (section 4.2.3)

**Comment by ryanpdx** [comment]
device tree path [image_builder/device_tree/am335x-oresat-card.dts](https://github.com/oresat/oresat-linux/blob/master/image_builder/device_tree/am335x-oresat-card.dts)

**Comment by ryanpdx** [comment]
Random notes:

- `aes` and `sham` are cyrto hardware accelerators
- `sgx` does not exist anymore (i guess it was replace with `gpu`?)
- when diabling the `wkup_m3` (low power m3), uboot/linux does boot

**Comment by ryanpdx** [comment]
Everything not used should be disabled by now in [image_builder/device_trees/oresat-base.dtsi](https://github.com/oresat/oresat-linux/blob/master/image_builder/device_trees/oresat-base.dtsi).

All device trees should include that file and then re-enable and re-configure anything needed by that card.
